//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navette.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonnement()
        {
            this.USER_APP = new HashSet<USER_APP>();
            this.Abo_Client = new HashSet<Abo_Client>();
        }
    
        public int ID_Abonnement { get; set; }
        public Nullable<int> ID_Societe { get; set; }
        [Required(ErrorMessage ="This field is required")]
        public Nullable<int> ID_Autocar { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> Date_Debut { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> Date_Fin { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.TimeSpan> Heure_Depart { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.TimeSpan> Heure_Arrive { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> Nombre_Passager { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> Ville_Depart { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> Ville_Arrive { get; set; }
         [Required(ErrorMessage ="This field is required")]
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> nombre_inscrit { get; set; }
        public int inscrits { get; set; }
    
        public virtual Autocar Autocar { get; set; }
        public virtual Societe Societe { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_APP> USER_APP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abo_Client> Abo_Client { get; set; }
    }
}
