//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggestion
    {
        public int Id_Suggestion { get; set; }
        public string Ville_Depart { get; set; }
        public string Ville_Arrive { get; set; }
        public Nullable<System.TimeSpan> Heure_depart { get; set; }
    }
}
